"""12

Revision ID: 1cf2a7f1685f
Revises: baf9d389d8fc
Create Date: 2024-03-23 19:33:20.248720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf2a7f1685f'
down_revision: Union[str, None] = 'baf9d389d8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('target_relation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'target_relation')
    # ### end Alembic commands ###
