"""12

Revision ID: 2dc3661c39e7
Revises: 2b4e48a8113e
Create Date: 2024-03-23 15:51:55.481289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc3661c39e7'
down_revision: Union[str, None] = '2b4e48a8113e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pw', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_user_seq'), 'user', ['seq'], unique=False)
    op.create_table('target',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_seq', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(), nullable=False),
    sa.Column('target_add_datetime', sa.DateTime(), nullable=False),
    sa.Column('target_history', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_seq'], ['user.seq'], ),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_target_seq'), 'target', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_seq'), table_name='target')
    op.drop_table('target')
    op.drop_index(op.f('ix_user_seq'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
