"""12

Revision ID: 82fe77568ad9
Revises: 1cf2a7f1685f
Create Date: 2024-03-23 19:46:44.016527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fe77568ad9'
down_revision: Union[str, None] = '1cf2a7f1685f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('target_kakao_chat', sa.String(), nullable=True))
    op.alter_column('target', 'target_history',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target', 'target_history',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('target', 'target_kakao_chat')
    # ### end Alembic commands ###
