"""12

Revision ID: baf9d389d8fc
Revises: 2dc3661c39e7
Create Date: 2024-03-23 19:05:07.713649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf9d389d8fc'
down_revision: Union[str, None] = '2dc3661c39e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('target_lost_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'target_lost_date')
    # ### end Alembic commands ###
