"""12

Revision ID: cd5422c9907d
Revises: 82fe77568ad9
Create Date: 2024-03-23 20:09:15.982401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5422c9907d'
down_revision: Union[str, None] = '82fe77568ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_seq', sa.Integer(), nullable=True),
    sa.Column('target_seq', sa.Integer(), nullable=True),
    sa.Column('diary_dday', sa.Integer(), nullable=False),
    sa.Column('diary_content', sa.String(), nullable=False),
    sa.Column('diary_add_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_seq'], ['target.seq'], ),
    sa.ForeignKeyConstraint(['user_seq'], ['user.seq'], ),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_diary_seq'), 'diary', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diary_seq'), table_name='diary')
    op.drop_table('diary')
    # ### end Alembic commands ###
